# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adservice_manager_pb2 as adservice__manager__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in adservice_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdserviceManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractMicroserviceData = channel.unary_unary(
                '/adservice_manager.AdserviceManager/ExtractMicroserviceData',
                request_serializer=adservice__manager__pb2.MicroserviceDataRequest.SerializeToString,
                response_deserializer=adservice__manager__pb2.MicroserviceData.FromString,
                _registered_method=True)


class AdserviceManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractMicroserviceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdserviceManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractMicroserviceData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractMicroserviceData,
                    request_deserializer=adservice__manager__pb2.MicroserviceDataRequest.FromString,
                    response_serializer=adservice__manager__pb2.MicroserviceData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adservice_manager.AdserviceManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adservice_manager.AdserviceManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdserviceManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractMicroserviceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adservice_manager.AdserviceManager/ExtractMicroserviceData',
            adservice__manager__pb2.MicroserviceDataRequest.SerializeToString,
            adservice__manager__pb2.MicroserviceData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
