#!/bin/bash
kubectl.exe delete deployment adservicemanager cartservicemanager checkoutservicemanager currencyservicemanager emailservicemanager frontendmanager paymentservicemanager productcatalogservicemanager recommendationservicemanager rediscartmanager shippingservicemanager
kubectl.exe delete service adservicemanager cartservicemanager checkoutservicemanager currencyservicemanager emailservicemanager frontendmanager paymentservicemanager productcatalogservicemanager recommendationservicemanager rediscartmanager shippingservicemanager
