apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: knowledge-base
  labels: 
    type: local
spec: 
  storageClassName: manual
  capacity: 
    storage: 300Mi
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: knowledge-base-claim
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 300Mi
    

